const KEY='clipper-state-v1';
const state=JSON.parse(localStorage.getItem(KEY)||'null')||{accounts:[],clips:[],settings:{style:'Relatable',position:'Top',font:'Bold'},tab:'home'};
function save(){localStorage.setItem(KEY,JSON.stringify(state))}function uid(){return crypto.randomUUID?crypto.randomUUID():Date.now()+Math.random()}function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function app(){document.querySelector('#app').innerHTML=`<main class="shell"><div class="top"><div class="brand">Clipper</div><div class="pill">${state.clips.length} clips · ${state.accounts.length} sources</div></div><div id="view"></div></main><nav class="nav"><div class="navin"><button data-tab="home">⚡<br>Remix</button><button data-tab="library">▣<br>Library</button><button data-tab="settings">⚙<br>Settings</button></div></nav>`;render();document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;save();render()})}
function render(){document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===state.tab));const v=document.querySelector('#view');if(state.tab==='home')home(v);if(state.tab==='library')library(v);if(state.tab==='settings')settings(v)}
function home(v){const unused=state.clips.filter(c=>!c.used).length;v.innerHTML=`<section class="hero"><div class="eyebrow">Meme clipping engine</div><h1>10 clips.<br>One tap.</h1><p>Pick a batch, generate fresh hooks, remix the text and keep track of what you've already used.</p><button class="primary" id="random">RANDOM 10</button><div class="row" style="margin-top:10px"><button class="secondary" style="flex:1" id="add">＋ Inspiration account</button><button class="secondary" style="flex:1" id="import">＋ Import clips</button></div><div id="prog"></div></section><div class="grid"><div class="card"><div class="muted">Unused</div><div class="stat">${unused}</div></div><div class="card"><div class="muted">Ready</div><div class="stat">${state.clips.filter(c=>c.ready).length}</div></div></div><section class="section"><h2>Inspiration pool</h2>${state.accounts.length?state.accounts.map(a=>`<div class="account"><div class="avatar">${esc(a.handle.replace('@','').slice(0,1).toUpperCase())}</div><div><div class="name">${esc(a.name||a.handle)}</div><div class="handle">${esc(a.handle)}</div></div><div class="spacer"></div><span class="tag">${a.enabled?'ON':'OFF'}</span></div>`).join(''):'<div class="empty">Add meme inspiration accounts, then import clips from them or from your Photos library.</div>'}</section><section class="section"><h2>Latest batch</h2><div id="batch">${renderBatch()}</div></section>`;document.querySelector('#add').onclick=()=>accountSheet();document.querySelector('#import').onclick=()=>importInput();document.querySelector('#random').onclick=runRandom}
function renderBatch(){const arr=state.clips.filter(c=>c.batch).slice(-10).reverse();if(!arr.length)return'<div class="empty">No batch yet. Tap RANDOM 10.</div>';return arr.map(c=>`<div class="clip"><img class="thumb" src="${c.preview||'data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 width=%2288%22 height=%22118%22%3E%3Crect width=%22100%25%22 height=%22100%25%22 fill=%22%2322232a%22/%3E%3C/svg%3E'}"><div><span class="tag">${c.ready?'READY':'QUEUED'}</span><h3>${esc(c.name)}</h3><div class="muted">${esc(c.source||'Imported clip')}</div><div class="hook">${esc(c.hook||'Tap Remix to generate a hook.')}</div><div class="row" style="margin-top:8px"><button class="secondary" data-remix="${c.id}">Remix</button>${c.caption?`<button class="secondary" data-copy="${c.id}">Copy caption</button>`:''}</div></div></div>`).join('')}
function library(v){v.innerHTML=`<section class="hero"><div class="eyebrow">Library</div><h1>${state.clips.length} clips</h1><p>Used clips stay remembered so your random batches don't keep recycling the same content.</p><button class="primary" id="import">Import from Photos</button></section><section class="section">${state.clips.length?state.clips.slice().reverse().map(c=>`<div class="clip"><img class="thumb" src="${c.preview||'data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 width=%2288%22 height=%22118%22%3E%3Crect width=%22100%25%22 height=%22100%25%22 fill=%22%2322232a%22/%3E%3C/svg%3E'}"><div><span class="tag">${c.used?'USED':'UNUSED'}</span><span class="tag">${c.ready?'READY':'RAW'}</span><h3>${esc(c.name)}</h3><div class="muted">${esc(c.source||'Imported')}</div>${c.hook?`<div class="hook">${esc(c.hook)}</div>`:''}</div></div>`).join(''):'<div class="empty">Import videos to build your clipping library.</div>'}</section>`;document.querySelector('#import').onclick=importInput}
function settings(v){v.innerHTML=`<section class="hero"><div class="eyebrow">Settings</div><h1>Make it yours.</h1><p>These defaults control the remix engine.</p></section><section class="card"><label class="muted">Hook style</label><select class="input" id="style" style="margin-top:7px">${['Relatable','Chaotic','Savage','Dry','Curiosity','Identity'].map(x=>`<option ${state.settings.style===x?'selected':''}>${x}</option>`).join('')}</select><label class="muted" style="display:block;margin-top:15px">Text position</label><select class="input" id="position" style="margin-top:7px">${['Top','Center','Bottom'].map(x=>`<option ${state.settings.position===x?'selected':''}>${x}</option>`).join('')}</select><label class="muted" style="display:block;margin-top:15px">Font</label><select class="input" id="font" style="margin-top:7px">${['Bold','Clean','Meme'].map(x=>`<option ${state.settings.font===x?'selected':''}>${x}</option>`).join('')}</select><button class="secondary danger" style="width:100%;margin-top:18px" id="clear">Reset all local data</button></section>`;['style','position','font'].forEach(id=>document.querySelector('#'+id).onchange=e=>{state.settings[id]=e.target.value;save()});document.querySelector('#clear').onclick=()=>{if(confirm('Delete all Clipper data?')){localStorage.removeItem(KEY);location.reload()}}}
function accountSheet(){document.body.insertAdjacentHTML('beforeend',`<div class="sheet" id="sheet"><div class="modal"><h2>Add inspiration account</h2><p class="muted">Store the account in your pool. Media acquisition from arbitrary Instagram accounts is intentionally not faked; import/share the clips you are allowed to use.</p><input class="input" id="handle" placeholder="@account"><input class="input" id="name" placeholder="Optional name" style="margin-top:9px"><div class="row"><button class="secondary" id="cancel" style="flex:1">Cancel</button><button class="primary" id="saveAccount" style="flex:1">Add</button></div></div></div>`);document.querySelector('#cancel').onclick=closeSheet;document.querySelector('#saveAccount').onclick=()=>{let h=document.querySelector('#handle').value.trim();if(!h)return;state.accounts.push({id:uid(),handle:h.startsWith('@')?h:'@'+h,name:document.querySelector('#name').value.trim(),enabled:true});save();closeSheet();render()}}
function closeSheet(){document.querySelector('#sheet')?.remove()}
function importInput(){const i=document.createElement('input');i.type='file';i.accept='video/*';i.multiple=true;i.onchange=()=>handleFiles([...i.files]);i.click()}
async function handleFiles(files){for(const f of files){const url=URL.createObjectURL(f);const clip={id:uid(),name:f.name.replace(/\.[^.]+$/,''),source:'Photos / Files',preview:url,used:false,ready:false,fileName:f.name};state.clips.push(clip)}save();toast(`${files.length} clip${files.length>1?'s':''} imported`);render()}
function runRandom(){const pool=state.clips.filter(c=>!c.used);if(!pool.length){toast('Import some clips first');return}const selected=pool.sort(()=>Math.random()-.5).slice(0,10);const batch=Date.now();selected.forEach((c,i)=>{c.batch=batch;c.hook=makeHook(c);c.caption=makeCaption(c);c.ready=true;c.used=true});save();render();toast(`${selected.length} clips remixed`);window.scrollTo({top:document.body.scrollHeight,behavior:'smooth'})}
function makeHook(c){const s=state.settings.style;const n=c.name.toLowerCase();const base={Relatable:[`POV: you thought this was going to go differently`,`That moment when you realize you messed up`,`Everyone has that one moment they wish they could delete`],Chaotic:[`This escalated way faster than it needed to`,`Nobody had this on their 2026 bingo card`,`The exact second everything went off the rails`],Savage:[`The confidence was there. The plan was not.`,`This is where the whole situation fell apart`,`One decision. Immediate regret.`],Dry:[`Well, that went exactly as expected.`,`A completely normal decision with normal consequences.`,`Nothing to see here. Everything is fine.`],Curiosity:[`Watch the last few seconds before judging this`,`The ending changes the entire context`,`You need to see what happens after this`],Identity:[`If you've ever been the friend who says "trust me"`,`Every group has a person like this`,`POV: you're the one who always makes it worse`]};let a=base[s]||base.Relatable;return a[Math.floor(Math.random()*a.length)]}
function makeCaption(c){return `One of those moments that starts normally and somehow turns into the only part everyone remembers.\n\nRemixed for Clipper.`}
function remix(id){const c=state.clips.find(x=>x.id===id);if(!c)return;c.hook=makeHook(c);c.caption=makeCaption(c);c.ready=true;c.used=true;save();render();toast('Remixed')}
function toast(t){const d=document.createElement('div');d.className='toast';d.textContent=t;document.body.appendChild(d);setTimeout(()=>d.remove(),1800)}
function copy(id){const c=state.clips.find(x=>x.id===id);if(c?.caption)navigator.clipboard?.writeText(c.caption).then(()=>toast('Caption copied'))}
document.addEventListener('click',e=>{const r=e.target.closest('[data-remix]');if(r)remix(r.dataset.remix);const c=e.target.closest('[data-copy]');if(c)copy(c.dataset.copy)});app();
